core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('notes/', include('note.urls', namespace='notes'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path
from .views import *


app_name = 'notes'

urlpatterns = [
    path('view_note/', view_note, name='view_note'),
    path('add_note/', add_note, name='add_note'),
    path('edit_note/', edit_note, name='edit_note'),
    path('delete_note/', delete_note, name='delete_note'),

    path('tags/', all_tags, name='tags'),
    path('view_tag/', view_tag, name='view_tag'),
    path('add_tag/', add_tag, name='add_tag'),
    path('delete_tag/', delete_tag, name='delete_tag')
]

users/urls.py
from django.urls import path
from .views import (loginview, profile, signupview,
                    profile_settings, change_email, logoutview,
                    change_password, profile_search_notes, profile_settings_search_notes)


app_name = 'users'


urlpatterns = [
    path('login/', loginview, name='login'),
    path('signup/', signupview, name='signup'),
    path('profile/', profile, name='profile'),
    path('profile/settings/', profile_settings, name='profile_settings'),
    path('settings/change-email/', change_email, name='change_email'),
    path('settings/change-password/', change_password, name='change_password'),
    path('logout/', logoutview, name='logout'),
    path('profile/search-notes/', profile_search_notes, name='profile_search_notes'),
    path('profile/settings/search-notes/', profile_settings_search_notes, name='profile_settings_search_notes'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError


from .models import User



from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter your username',
            'class': 'form-control no_borders dark-input',
            'autocomplete': 'username',
            'required': 'required'
        })
    )
    password = forms.CharField(
        label='Passworda',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter your password',
            'class': 'form-control dark-input',
            'autocomplete': 'current-password',
            'required': 'required'
        })
    )


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control no_borders dark-input',}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control no_borders dark-input',}))

    class Meta:
        model = User
        fields = ('username', 'email')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control no_borders dark-input',}),
            'email': forms.TextInput(attrs={'class': 'form-control no_borders dark-input',}),
        }

class ChangeEmailForm(forms.ModelForm):
    current_password = forms.CharField(
        label="Current password",
        widget=forms.PasswordInput(attrs={'class': 'form-control no_borders dark-input'}),
        strip=False,
    )

    class Meta:
        model = User
        fields = ('email', )
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control no_borders dark-input'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


    def clean_current_password(self):
        password = self.cleaned_data.get('current_password')
        if not self.user.check_password(password):
            raise forms.ValidationError('Incorrect password')
        print('работает', password)
        return password
    


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control no_borders dark-input', 'placeholder': 'old password'})
    )
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control no_borders dark-input', 'placeholder': 'new password'})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control no_borders dark-input', 'placeholder': 'confirm new password'})
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        password = self.cleaned_data.get('old_password')
        if not self.user.check_password(password):
            raise forms.ValidationError('Incorrect current password')
        return password

    def clean_new_password(self):
        password = self.cleaned_data.get('new_password')
        try:
            validate_password(password, self.user)
        except ValidationError as e:
            raise forms.ValidationError(e.messages)
        return password

    def clean(self):
        cleaned_data = super().clean()
        new = cleaned_data.get('new_password')
        confirm = cleaned_data.get('confirm_password')
        if new and confirm and new != confirm:
            raise forms.ValidationError('New passwords do not match')
        return cleaned_data

    def save(self, commit=True):
        new_password = self.cleaned_data['new_password']
        self.user.set_password(new_password)
        if commit:
            self.user.save()
        return self.user

users/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages



from note.models import Note, Tag
from .forms import LoginForm, SignUpForm, ChangeEmailForm, ChangePasswordForm


def loginview(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('main:homepage'))
            else:
                messages.error(request, f"Incorrect password or username")
    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def signupview(request):
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You signup succesfully')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = SignUpForm()
    context = {'form': form}
    return render(request, 'users/signup.html', context) 


@login_required
def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:homepage'))


@login_required
def profile(request):
    notes = Note.objects.filter(user=request.user).order_by('-added_on')
    tags = Tag.objects.filter(user=request.user)
    context = {'notes': notes, 'tags': tags}

    return render(request, 'users/profile.html', context)

@login_required
def profile_search_notes(request):
    query = request.GET.get('q', '')  
    if query:
        notes = Note.objects.filter(title__icontains=query)
    else:

        notes = Note.objects.filter(user=request.user).order_by('-added_on')

    context = {
        'notes': notes
    }
    
    html = render_to_string('users/partials/search_result.html', context)
    
    return JsonResponse({'html': html})



@login_required
def profile_settings(request):
    return render(request, 'users/profile_settings.html')    


def profile_settings_search_notes(request):
    query = request.GET.get("q", "")
    results = []

    if query:
        notes = Note.objects.filter(title__icontains=query)[:5]
        results = [{'id': note.id, 'title': note.title} for note in notes]

    return JsonResponse({'results': results})




@login_required
def change_email(request):
    if request.method == 'POST':
        form = ChangeEmailForm(request.POST, instance=request.user, user=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile_settings'))

    else:
        form = ChangeEmailForm(instance=request.user, user=request.user)
    context = {'form': form}
    return render(request, 'users/change_email.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST, user=request.user)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return HttpResponseRedirect(reverse('users:profile_settings'))
    else:
        form = ChangePasswordForm(user=request.user)
    return render(request, 'users/change_password.html', {'form': form})

users/templates/users/change_email.html
{% extends "base.html" %}

{% block content %}
    <div class="container" style="padding-top: 2%">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form method="post" action="{% url 'users:change_email' %}">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3 col-lg-offset-3 text-center">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                            <ul>
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                    <br>
                    <h3 style="color: #33FF00;">New email</h3>
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="alert alert-danger" style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                            <ul class="list-unstyled">
                                {% for error in form.email.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <br>

                    <h3 style="color: #33FF00;">Current password</h3>
                    <br>
                    {{ form.current_password }}
                    {% if form.current_password.errors %}
                        <div class="alert alert-danger" style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                            <ul class="list-unstyled">
                                {% for error in form.current_password.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <br>

                    <button type="submit" class="form-control btn btn-primary" style="background-color: #000000; border: 1px solid #33FF00; color: #33FF00; transition: background-color 0.3s ease;">
                        Change Email
                    </button>
                </div>
            </form>
        </div>
    </div>

    <style>
        
    </style>
{% endblock %}

users/templates/users/change_password.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="padding-top: 2%">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form method="post" action="{% url 'users:change_password' %}">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3 col-lg-offset-3 text-center">
                    {% csrf_token %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                        {{ error }}
                    </div>
                {% endfor %}

                    
                    <div style="margin-bottom: 20px;">
                        <h3 style="color: #33FF00;">{{ form.old_password.label }}</h3>
                        {{ form.old_password }}
                        {% for message in form.old_password.errors %}
                            <div class="alert">{{ message }}</div>
                        {% endfor %}
                    </div>
                    
                    <div style="margin-bottom: 20px;">
                        <h3 style="color: #33FF00;">{{ form.new_password.label }}</h3>
                        {{ form.new_password }}
                        {% for message in form.new_password.errors %}
                            <div class="alert">{{ message }}</div>
                        {% endfor %}
                    </div>

                    <div style="margin-bottom: 20px;">
                        <h3 style="color: #33FF00;">{{ form.confirm_password.label }}</h3>
                        {{ form.confirm_password }}
                        {% for message in form.confirm_password.errors %}
                            <div class="alert">{{ message }}</div>
                        {% endfor %}
                    </div>

                    <button type="submit" class="form-control btn btn-primary" style="background-color: #000000; border: 1px solid #33FF00; color: #33FF00; transition: background-color 0.3s ease;">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>

    <style>
        /* Убираем серые обводки и стили при фокусе */
       
    </style>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container" style="padding-top: 2%">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3 col-lg-offset-3 text-center">

            <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                
                {% for error in messages %}
                    <div class="alert alert-danger" style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                        {{ error }}
                    </div>
                {% endfor %}

                <div style="margin-bottom: 20px;">
                    <label style="color: #33FF00; font-size: 14px; float: left;">{{ form.username.label }}</label>
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="alert alert-danger" style="background-color: #000; color: #33FF00; border: 1px solid #33FF00;">
                            <ul class="list-unstyled">
                                {% for error in form.username.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>

                <div style="margin-bottom: 20px;">
                    <label style="color: #33FF00; font-size: 14px; float: left;">{{ form.password.label }}</label>
                    {{ form.password }}
                    {% if form.password.errors %}
                        <div class="alert alert-danger" style="background-color: #000; color: #33FF00; border: 1px solid #33FF00;">
                            <ul class="list-unstyled">
                                {% for error in form.password.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>

                <button type="submit" class="form-control btn btn-primary" style="background-color: #000; border: 1px solid #33FF00; color: #33FF00;">
                    Log in
                </button>
            </form>

            <h5 style="color: #33FF00;">Don't have an account? 
                <a href="{% url 'users:signup' %}" style="color: #33FF00;">Sign Up</a>
            </h5>
        </div>
    </div>

    <style>
        
    </style>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <div class="container" style="padding-top: 2%; color: #33FF00;">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                {% if delete %}
                    <div class="alert alert-danger" style="background-color: #111; border: 1px solid #33FF00; color: #33FF00;">
                        <button type="button" class="close" data-dismiss="alert" style="color: #33FF00;">&times;</button>
                        Note deleted successfully
                    </div>
                {% endif %}

                <h1 style="color: #33FF00;">Welcome, {{ user.username }}</h1>

                {% if notes %}
                <input type="text" id="notes" class="form-control dark-input no_borders"
                autocomplete="off" name="notes" placeholder="Search Note">

                <div style="padding-top: 20px">
                    <div id="result">{% include 'users/partials/search_result.html' %}</div>
                </div>
                    <br>
                {% else %}
                    <div class="alert alert-danger" style="background-color: #111; border: 1px solid #33FF00; color: #33FF00;">
                        You have no notes added! Let's add one <a href="/notes/add/" style="color: #33FF00; text-decoration: underline;">here</a>
                    </div>
                {% endif %}
        </div>
    </div>
    <style>

        
    </style>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#notes").keyup(function () {
                let query = $(this).val(); 
    
                if (query.length > 0) {
                    $.ajax({
                        url: "{% url 'users:profile_search_notes' %}",
                        data: {
                            'q': query
                        },
                        dataType: 'json',
                        success: function (data) {
                            $("#result").html(data['html']);
                        }
                    });
                } else {
                    $.ajax({
                        url: "{% url 'users:profile_search_notes' %}",
                        data: {
                            'q': '' 
                        },
                        dataType: 'json',
                        success: function (data) {
                            $("#result").html(data['html']);
                        }
                    });
                }
            });
        });
    </script>
    
{% endblock %}

users/templates/users/profile_settings.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
    <div class="container" style="padding-top: 2%">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div style="padding: 3%; background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                <legend><h3 class="text-center" style="color: #33FF00;"><b>User Details:</b></h3></legend>
                <h4><b>Registered on:</b> <br><br> {{ user.created | naturaltime}}</h4>
                <br>
                <h4><b>Last Logged in on:</b> <br><br> {{ user.last_login | naturaltime }}</h4>
                <br>
                <h4><b>Email: <a href="{% url 'users:change_email' %}" style="color: #33FF00;"><span class="glyphicon glyphicon-pencil"></span></a></b> <br><br>{{ user.email }}</h4>
                <br>
                <h4><b>Username:</b> <br><br> {{ user.username }}</h4>
            </div>
        </div> <!-- ./column -->

        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div style="padding: 3%; background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                <a href="{% url 'users:profile' %}" style="color: #33FF00; text-decoration: none;">
                    <h3>Notes <span class="badge" style="background-color: #33FF00;">{{ notes_count }}</span></h3>
                </a>
                <input type="text" id="notes" class="form-control no_borders"
                       autocomplete="off" name="notes"
                       placeholder="Search Note"
                       style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">

                <!-- таблица для отображения результатов -->
                <table id="suggestions" style="width: 100%; border-collapse: collapse; display: none;">
                    <thead>
                        <tr style="background-color: #1a1a1a; color: #33FF00;">
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

                <div style="padding-top: 20px">
                    <div id="result"></div>
                </div>
                <br>
                <a href="{% url 'notes:tags' %}" style="color: #33FF00; text-decoration: none;">
                    <h3>Tags <span class="badge" style="background-color: #33FF00;">{{ tag_count }}</span></h3>
                </a>
            </div>
        </div>
    </div>
    <script>
document.addEventListener("DOMContentLoaded", function () {
    const input = document.getElementById("notes");
    const suggestions = document.getElementById("suggestions");
    const tbody = suggestions.querySelector("tbody");

    input.addEventListener("input", function () {
        const query = input.value;

        if (query.length < 1) {
            suggestions.style.display = "none";  // скрыть таблицу, если ничего не введено
            return;
        }

        fetch(`/users/profile/settings/search-notes/?q=${encodeURIComponent(query)}`)
            .then(response => response.json())
            .then(data => {
                tbody.innerHTML = "";  // очищаем таблицу перед добавлением новых данных

                if (data.results.length === 0) {
                    suggestions.style.display = "none";  // если нет результатов, скрываем таблицу
                    return;
                }

                suggestions.style.display = "table";  // показываем таблицу с результатами

                data.results.forEach(note => {
                    const row = document.createElement("tr");
                    row.style.borderBottom = "1px solid #33FF00";  // зелёная линия

                    const cell = document.createElement("td");
                    cell.textContent = note.title;
                    cell.style.padding = "10px";
                    cell.style.cursor = "pointer";
                    cell.style.color = "#33FF00";

                    // Делаем клик на строке, чтобы перейти к note
                    cell.onclick = () => {
                        window.location.href = `/notes/view_note/?note=${note.id}`;
                    };

                    row.appendChild(cell);
                    tbody.appendChild(row);
                });
            });
    });
});
</script>

        
{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}

{% block content %}
    <div class="container" style="padding-top: 2%">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3 col-lg-offset-3">

            <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}

                <div style="margin-bottom: 20px;">
                    {{ form.username.label }}
                    {{ form.username }}
                </div>

                <div style="margin-bottom: 20px;">
                    {{ form.email.label }}
                    {{ form.email }}
                </div>

                <div style="margin-bottom: 20px;">
                    {{ form.password1.label }}
                    {{ form.password1 }}
                </div>

                <div style="margin-bottom: 20px;">
                    {{ form.password2.label }}
                    {{ form.password2 }}
                </div>

                <button type="submit" class='form-control btn btn-primary no_borders' style="background-color: #000000; border: 1px solid #33FF00; color: #33FF00;">Sign up</button>
            </form>

            <h5 style="margin-top: 15px; color: #33FF00;">Already have an account? 
                <a href="{% url 'users:login' %}" style="color: #33FF00; text-decoration: underline;">Log In</a>
            </h5>
        </div>
    </div>

    <style>

    </style>
{% endblock %}