core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('notes/', include('note.urls', namespace='notes'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path
from .views import *


app_name = 'notes'

urlpatterns = [
    path('view_note/', view_note, name='view_note'),
    path('add_note/', add_note, name='add_note'),
    path('edit_note/', edit_note, name='edit_note'),
    path('delete_note/', delete_note, name='delete_note'),

    path('tags/', all_tags, name='tags'),
    path('view_tag/', view_tag, name='view_tag'),
    path('add_tag/', add_tag, name='add_tag'),
    path('delete_tag/', delete_tag, name='delete_tag')
]

note/models.py
from django.db import models
from users.models import User


class Tag(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tags') # user.tags.all() 

    class Meta:
        unique_together = ('name', 'user')

    def __str__(self):
        return self.name

class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True,)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

note/forms.py
from django import forms
from django.shortcuts import get_list_or_404

from users.models import User
from note.models import Note, Tag


class AddNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'tags']  
        widgets = {
            'title': forms.Textarea(attrs={'class': 'form-control dark-input'})
        }        

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
    
        self.fields['tags'].queryset = Tag.objects.filter(user=self.user)


    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'tag form-control dark-input'}),
        required=False
    )

    content = forms.CharField(
        label="Content",
        widget=forms.Textarea(attrs={
            'class': 'form-control dark-input',
            'rows': 20,
            'cols': 90,
            'placeholder': 'Write your note here'
        })
    )


class EditNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'tags']  
        widgets = {
            'title': forms.Textarea(attrs={'class': 'form-control dark-input'})
        }        

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
    
        self.fields['tags'].queryset = Tag.objects.filter(user=self.user)


    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'tag form-control dark-input'}),
        required=False
    )

    content = forms.CharField(
        label="Content",
        widget=forms.Textarea(attrs={
            'class': 'form-control dark-input',
            'rows': 20,
            'cols': 90,
            'placeholder': 'Write your note here'
        })
    )



class AddTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control dark-input no_borders'})
        }

note/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseForbidden
from django.contrib.auth.decorators import login_required

from .models import Note, Tag
from .forms import AddNoteForm, AddTagForm, EditNoteForm

@login_required
def view_note(request):
    notes = Note.objects.filter(user=request.user)
    note_id = request.GET.get('note')
    note = get_object_or_404(notes, id=note_id)

    context = {'note': note}
    return render(request, 'note/view_note.html', context)


@login_required
def add_note(request):
    if request.method == 'POST':
        form = AddNoteForm(data=request.POST, user=request.user)
        if form.is_valid():
            note = form.save(commit=False)
            note
            note.user = request.user
            note.save() 
            form.save_m2m() 
            return HttpResponseRedirect(reverse('users:profile_settings'))
    else:
        form = AddNoteForm(user=request.user)
    context = {'form': form}
    return render(request, 'note/add_note.html', context)



@login_required
def edit_note(request):
    note_id = request.GET.get('note')
    note = get_object_or_404(Note, id=note_id)
    if request.method == 'POST':
        form = EditNoteForm(data=request.POST, user=request.user, instance=note)
        if form.is_valid():
            form.save()
            url = f'{reverse('notes:view_note')}?note={note_id}'
            return HttpResponseRedirect(url)
    else:
        form = EditNoteForm(instance=note, user=request.user)
    context = {'form': form,
               'note': note}
    return render(request, 'note/edit_note.html', context)


@login_required
def all_tags(request):
    tags = Tag.objects.filter(user=request.user)
    context = {'tags': tags,}
    return render(request, 'note/edit_tag.html', context)


@login_required
def view_tag(request):
    tags = Tag.objects.filter(user=request.user)
    tag_id = request.GET.get('tag')
    tag = get_object_or_404(tags, id=tag_id)
    notes = Note.objects.filter(user=request.user, tags=tag)
    context = {'tag': tag, 'notes': notes}
    return render(request, 'note/view_tag.html', context)


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = AddTagForm(data=request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return HttpResponseRedirect(reverse('notes:tags'))
    else:
        form = AddTagForm()
    context = {'form': form}

    return render(request, 'note/add_tag.html', context)


@login_required
def delete_tag(request):
    if request.method == 'POST':
        tag_id = request.POST.get('tag') 
        tag = get_object_or_404(Tag, id=tag_id, user=request.user)  
        tag.delete()  
        return redirect('notes:tags') 
    return HttpResponseForbidden("Forbidden")  
   

@login_required
def delete_note(request):
    if request.method == 'POST':
        tag_id = request.POST.get('note')  
        tag = get_object_or_404(Note, id=tag_id, user=request.user)  
        tag.delete()  
        return redirect('notes:profile')  
    return HttpResponseForbidden("Forbidden")  
   

note/templates/note/add_note.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

            <form method="POST" action="{% url 'notes:add_note' %}">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    {% csrf_token %}

                    <h3>{{ form.title.label }}</h3>
                    <br>
                    {{ form.title }}
                    <br>
                    {% if form.tags %}
                    <h3>{{ form.tags.label }}</h3>
                    <br>
                    {{ form.tags }}</h3>
                    {% endif %}
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="inline-headers">
                        <h3> Note: </h3>

                        <h5>
                        </h5>
                    </div>
                    <br>
                    {{ form.content }}
                    <br>
                <button type="submit" class="form-control btn btn-primary" style="background-color: #000; border: 1px solid #33FF00; color: #33FF00;">
                    Save note
                </button>
                </div>
            </form>
        </div>
    </div>
    <style>
        
        
    </style>
    <script>
        
    </script>
{% endblock %}

note/templates/note/add_tag.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">


            <form method="post" action="{% url 'notes:add_tag' %}">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3 col-lg-offset-3 text-center">
                    {% csrf_token %}
                    
                    <h3>New tag</h3>
                    <br>
                    {{ form.name }}
                    <br>
                    <button type="submit" class="form-control btn btn-primary" style="background-color: #000; border: 1px solid #33FF00; color: #33FF00;">
                        Save tag
                    </button>
                </div>
            </form>
        </div>
    </div>

    <style>
       
    </style>
{% endblock %}

note/templates/note/edit_note.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form method="post" action="{% url 'notes:edit_note' %}?note={{ note.id }}">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    {% csrf_token %}

                    <h3>{{ form.note_id }}</h3>
                    <br>
                    <h3>{{ form.title.label }}</h3>
                    <br>
                    {{ form.title }}
                    <br>
                    {% if form.tags %}
                    <h3>{{ form.tags.label }}</h3>
                    <br>
                    {{ form.tags }}</h3>
                    {% endif %}
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="inline-headers">
                        <h3> {{ form.content.label }} </h3>
                    </div>
                    <br>
                    {{ form.content }}
                    <br>
                    <input type="submit" value="Update" class='form-control no_borders btn btn-primary'>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

note/templates/note/edit_tag.html
{% extends "base.html" %}

{% block content %}
    <div class="container" style="padding-top: 2%;">
            <br>

            <h1 style="color: #33FF00;">Welcome, {{ user.username }}</h1>

            {% if tags %}
                <table class="table table-hover table-bordered"
                       style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                    <thead class="text-center" style="background-color: #111;">
                        <tr style="color: #33FF00;">
                            <th>Tag</th>
                            <th class="text-center">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tag in tags %}
                            <tr style="background-color: #000;">
                                <td>
                                    <a href="{% url 'notes:view_tag' %}?tag={{ tag.id }}" class="tag-link">{{ tag.name }}</a>
                                </td>
                                <td class="text-center">
                                    <form action="{% url 'notes:delete_tag' %}" method="POST" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="tag" value="{{ tag.id }}">
                                        <button type="submit" style="background: none; border: none; padding: 0;">
                                            <span class="glyphicon glyphicon-trash" style="color: #33FF00;"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="alert alert-danger" style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                    You have no tags added! Let's add one <a href="{% url 'notes:add_tag' %}" style="color: #33FF00; text-decoration: underline;">here</a>
                </div>
            {% endif %}
        </div>
    </div>

    <style>
        
    </style>
{% endblock %}

note/templates/note/view_note.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
                    
    <div class="container" style="padding-top: 2%; color: #33FF00;">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="thumbnail" style="padding: 3%; background-color: #000; border: 1px solid #33FF00;">

                    <legend><h3 class="text-center" style="color: #33FF00;"><b>Note Details:</b></h3></legend>
                    <h4><b>Note Added on:</b><br><br> {{ note.added_on | naturaltime }}</h4>
                    <br>
                    <h4><b>Note Updated on:</b><br><br> {{ note.updated_on | naturaltime }}</h4>
                    <br>
                    <h4><b>Note Title:</b><br><br> {{ note.title }}</h4>
            </div>
        </div>

        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="thumbnail" style="padding: 3%; background-color: #000; border: 1px solid #33FF00;">

                <div class="d-flex justify-content-between" style="margin-bottom: 20px; height: 40px;">
                        <a href="{% url 'notes:edit_note' %}?note={{ note.id }}" class="pull-left">
                            <button type="button" class="btn btn-outline-info" style="color: #33FF00; border-color: #33FF00; background-color: #000;">
                                <span class="glyphicon glyphicon-edit"></span> Edit
                            </button>
                        </a>

                        <form action="{% url 'notes:delete_note' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="tag" value="{{ note.id }}">
                            <button type="submit" style="background: none; border: none; padding: 0;">
                                <span class="glyphicon glyphicon-trash" style="color: #33FF00;"></span>
                            </button>
                        </form>
                    </td>
                    </div>

                    <h2 style="color: #33FF00;">{{ note.content }}</h2>
            </div>
        </div>

    </div>
{% endblock %}

note/templates/note/view_tag.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="padding-top: 2%">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h2 style="color: #33FF00;">Notes tagged under: {{ tag }}</h2>
            <br>
            {% if notes %}
                <table class="text-center table table-hover table-striped table-bordered"
                       style="background-color: #000; color: #33FF00; border: 1px solid #33FF00;">
                    <thead class="d-flex text-center" style="background-color: #111;">
                        <tr style="color: #33FF00;">
                            <th class="text-center">Note Title</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for note in notes %}
                            <tr>
                                <td colspan="2">
                                    <a href="{% url 'notes:view_note' %}?note={{ note.id }}" class="tag-link">{{ note.title }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="alert alert-danger"
                     style="background-color: #000000; color: #33FF00; border: 1px solid #33FF00;">
                    You have no notes added under this tag!
                </div>
            {% endif %}
        </div>
    </div>

    <style>
        
    </style>
{% endblock %}