core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('notes/', include('note.urls', namespace='notes'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path
from .views import *


app_name = 'notes'

urlpatterns = [
    path('view_note/', view_note, name='view_note'),
    path('add_note/', add_note, name='add_note'),
    path('edit_note/', edit_note, name='edit_note'),
    path('delete_note/', delete_note, name='delete_note'),

    path('tags/', all_tags, name='tags'),
    path('view_tag/', view_tag, name='view_tag'),
    path('add_tag/', add_tag, name='add_tag'),
    path('delete_tag/', delete_tag, name='delete_tag')
]

users/urls.py
from django.urls import path
from .views import (loginview, profile, signupview,
                    profile_settings, change_email, logoutview,
                    change_password, profile_search_notes, profile_settings_search_notes)


app_name = 'users'


urlpatterns = [
    path('login/', loginview, name='login'),
    path('signup/', signupview, name='signup'),
    path('profile/', profile, name='profile'),
    path('profile/settings/', profile_settings, name='profile_settings'),
    path('settings/change-email/', change_email, name='change_email'),
    path('settings/change-password/', change_password, name='change_password'),
    path('logout/', logoutview, name='logout'),
    path('profile/search-notes/', profile_search_notes, name='profile_search_notes'),
    path('profile/settings/search-notes/', profile_settings_search_notes, name='profile_settings_search_notes'),

]

templates/base.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ title }}</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        &lt Take Notes &gt
                    </a>
                </div><!-- ./navbar-header -->
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" id="navbar-links">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'notes:add_note' %}">NEW NOTE</a></li>
                            <li><a href="{% url 'users:profile' %}">VIEW ALL NOTES</a></li>
                            <li><a href="{% url 'notes:add_tag' %}">NEW TAG</a></li>
                            <li><a href="{% url 'notes:tags' %}">VIEW ALL TAGS</a></li>
                        {% else %}
                            <li><a href="/"> HOME </a></li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    Welcome, {{ user.username }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'users:profile_settings' %}" class="dropdown-item">
                                            <span class="glyphicon glyphicon-cog"></span> Profile Settings
                                        </a>
                                    </li>
                                    <li><a href="{% url 'users:change_password' %}" class="dropdown-item">
                                            <span class="glyphicon glyphicon-wrench"></span> Update Password
                                        </a>
                                    </li>
                                    <li><a href="{% url 'users:logout' %}" class="dropdown-item">
                                            <span class="glyphicon glyphicon-log-out"></span> Logout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'users:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
                            <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
                        {% endif %}
                    </ul>
                    
                </div><!--/.nav-collapse -->
            </div><!-- ./container-->
        </nav>
        <div class="add-margin-top"></div>
        
        {% block content %}
        {% endblock %}
        
        <div class="add-margin-bottom"></div>
        <div class="container inline-p">
            <legend></legend>
        </div>

        <!-- jQuery, Bootstrap JS, and custom scripts -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/base.js' %}"></script>
        <script src="{% static 'js/typed.min.js' %}"></script>

        <script type="text/javascript">
            var typed3 = new Typed('.element', {
                strings: ['A Simple Note Taking App', 'A Simple Web App', 'A Simple Note Taking  Web App'],
                typeSpeed: 100,
                backSpeed: 100,
                smartBackspace: true,
                loop: true,
            });
        </script>
    </body>
</html>